# Generated by Django 2.2.2 on 2019-08-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0006_auto_20170526_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='required',
            field=models.BooleanField(blank=True, help_text='If enabled, a user must select an item from this category.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='speakerdiscount',
            name='is_copresenter',
            field=models.BooleanField(blank=True, help_text='This condition is met if the user is a copresenter of a presentation.'),
        ),
        migrations.AlterField(
            model_name='speakerdiscount',
            name='is_presenter',
            field=models.BooleanField(blank=True, help_text='This condition is met if the user is the primary presenter of a presentation.'),
        ),
        migrations.AlterField(
            model_name='speakerflag',
            name='is_copresenter',
            field=models.BooleanField(blank=True, help_text='This condition is met if the user is a copresenter of a presentation.'),
        ),
        migrations.AlterField(
            model_name='speakerflag',
            name='is_presenter',
            field=models.BooleanField(blank=True, help_text='This condition is met if the user is the primary presenter of a presentation.'),
        ),
    ]
