# Generated by Django 2.2.2 on 2019-10-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0009_auto_20191029_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pay_what_you_want',
            field=models.BooleanField(default=False, verbose_name='Pay What You Want'),
        ),
    ]
