# Generated by Django 2.2.2 on 2019-10-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0010_product_pay_what_you_want'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
