# Generated by Django 2.2.2 on 2019-10-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0011_productitem_price_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='render_type',
            field=models.IntegerField(choices=[(1, 'Radio button'), (2, 'Quantity boxes'), (3, 'Product selector and quantity box'), (4, 'Checkbox button'), (5, 'User Selected Amount'), (7, 'User Selected Amount and quantity box'), (6, 'Checkbox/Quantity Hybrid')], help_text='The registration form will render this category in this style.', verbose_name='Render type'),
        ),
    ]
