# Generated by Django 2.2.2 on 2019-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0012_auto_20191030_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='access_code',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
