# Generated by Django 2.2.2 on 2019-11-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0013_auto_20191030_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='form_css_class',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='CSS Class for container holding product fields'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_css_class',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='CSS Class for each product field'),
        ),
    ]
