# Generated by Django 2.2.2 on 2019-11-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0014_auto_20191104_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_line_item',
            field=models.BooleanField(default=False, verbose_name='Hide LineItem'),
        ),
    ]
