# Generated by Django 2.2.2 on 2019-11-11 17:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0015_product_hide_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
