# Generated by Django 2.2.2 on 2019-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0018_product_allow_housing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_donation',
            field=models.BooleanField(default=False),
        ),
    ]
