# Generated by Django 2.2.2 on 2019-11-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0019_product_is_donation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'permissions': (('registrasion_admin', 'Registrasion Admin'),)},
        ),
    ]
