# Generated by Django 2.2.2 on 2019-11-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0020_auto_20191118_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
