# Generated by Django 2.2.2 on 2019-11-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0021_lineitem_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
    ]
