# Generated by Django 2.2.2 on 2019-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0022_lineitem_is_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Voucher code'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='recipient',
            field=models.CharField(max_length=128, verbose_name='Recipient'),
        ),
    ]
